version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AdoptameNa
    ports:
      - "8080:8080"
  restart: unless-stopped
  environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_DATASOURCE_URL=jdbc:mysql://adoptamena-api.rodrigomaidana.com:3306/adoptamenatests?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Asuncion
    - SPRING_DATASOURCE_USERNAME=adoptamena-api
    - SPRING_DATASOURCE_PASSWORD=adoptamenadb2025
