name: Dev CI/CD Deployment

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy via SSH
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        # Copy .jar to /tmp/
        sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no target/*.jar $SSH_USER@$SSH_HOST:/tmp/

        # Luego, en el servidor remoto, mueve el archivo al directorio con sudo
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo '$SSH_PASS' | sudo -S mv /tmp/*.jar /etc/opt/adoptamena/dev/"

        # Restart Service
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo '$SSH_PASS' | sudo -S systemctl restart adoptamena-dev-service.service"
