name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main, test, dev ]  # Cambia a tu rama principal si es diferente

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v3
      
      # Build con Docker Compose
      - name: AdoptameNa
        run: docker compose build --no-cache
      
      # Despliegue con Docker Compose
      - name: AdoptameNa
        run: |
          docker compose down || true
          docker compose up -d
      
      # Verificar despliegue
      - name: Verificar despliegue
        run: |
          echo "Esperando a que la aplicaci칩n inicie..."
          sleep 20
          curl -f http://localhost:8080/actuator/health || echo "Verificaci칩n de salud fallida, pero continuando..."
      
      # Limpiar im치genes antiguas
      - name: Limpieza
        run: docker image prune -f
